name: Ramadan
version: '${version}'
main: me.threefour.ramadan.Ramadan
api-version: 1.19
authors: [ ThreeFour ]
description: A Ramadan In Minecraft Plugin
commands:
  quest:
    description: "View available quests or complete a quest."
    usage: "/quest [quest name]"
    permission: ramadan.quest
    permission-message: "You do not have permission to use this command."
    executor: me.threefour.ramadan.commands.QuestCommand
  stopfasting:
    description: Stops the player's fasting
    usage: /stopfasting
    permission: ramadan.stopfasting
    aliases: [ stopfast, sf ]
  ramadan:
    description: "Main command for the Ramadan plugin"
    usage: "/ramadan <subcommand>"
    permission: ramadan.reload
    permission-message: "You do not have permission to use this command."
    executor: me.threefour.ramadan.commands.ReloadCommand
    subcommands:
      reload:
        description: "Reload the configuration files for the plugin"
        usage: "/ramadan reload [config|messages]"
        permission: ramadan.reload
        permission-message: "You do not have permission to use this command."
        executor: me.threefour.ramadan.commands.ReloadCommand
  iftar:
    description: Set or teleport to the Iftar table location.
    usage: /iftar <set|tp|get>
    permission: ramadan.iftar
    subcommands:
      set:
        description: Set the Iftar table location.
        usage: /iftar set <x> <y> <z>
        permission: ramadan.iftar
      tp:
        description: Teleport to the Iftar table location.
        usage: /iftar tp
        permission: ramadan.iftar
      get:
        description: Get the Iftar table location as a compass.
        usage: /iftar get
        permission: ramadan.iftar
      help:
        description: Get help on how to use the iftar command.
        usage: /iftar help
        permission: ramadan.iftar
softdepend: [PlaceholderAPI]
