version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "java.runtime.version=17" >> gradle.properties
      - run:
          name: Grant Permssion
          command: chmod +x gradlew
      - run:
          name: Build plugin
          command: ./gradlew build
      - store_artifacts:
          path: build/libs/
          destination: Ramadan-1.0.2

workflows:
  version: 2
  build:
    jobs:
      - build
