name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          java-home: ${{ env.JAVA_HOME }}
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Three Four"
          git config --global user.email "threefourcontact@gmail.com"

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
            This is the first release of the project.
          draft: true
          prerelease: false

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: Ramadan-1.0.0.jar
          path: build/libs/Ramadan-1.0.0.jar
